// Generated by CoffeeScript 1.3.3
(function() {
  var convert, key, value, _ref;

  convert = function() {
    return false;
  };

  _ref = {
    convert: convert
  };
  for (key in _ref) {
    value = _ref[key];
    exports[key] = value;
  }

}).call(this);
